<?php

/**
 * Alternative grid config for imagefield
 * @author  Luis Santiago "blad"
 * 
 * ProcessWire 2.x 
 * Copyright (C) 2010 by Ryan Cramer 
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 * 
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class AlternativeGridImages extends WireData implements Module {

    public static function getModuleInfo() {
        return array(
            'title' => 'Alternative grid for multiple images', 
            'version' => 107, 
            'summary' => "This module show an alternative grid system in multiple images (not files).",
            'href' => 'https://github.com/LuisSantiago/AlternativeGridImages',
            'author' => 'Blad',
            'autoload' => true
            );
    }

    public function init() {
            $this->addHookBefore('InputfieldImage::render', $this, 'altGridconfigBefore');
        }
        
    public function altGridconfigBefore(HookEvent $event) {
                $this->config->scripts->add($this->config->urls->AlternativeGridImages . 'AlternativeGridImages.js'); 
                $this->config->scripts->add($this->config->urls->AlternativeGridImages . 'jquery.cookie.js'); 
                $this->config->styles->add($this->config->urls->AlternativeGridImages . 'AlternativeGridImages.css');                
         }
}
