<?php

/**
 * Alternative grid config for imagefield
 * @author  Luis Santiago "blad"
 * 
 * ProcessWire 2.x 
 * Copyright (C) 2010 by Ryan Cramer 
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 * 
 * http://www.processwire.com
 * http://www.ryancramer.com
 *
 */

class altGrid extends WireData implements Module, ConfigurableModule {

    public static function getModuleInfo() {
        return array(
            'title' => 'Alternative grid for multiple images/files', 
            'version' => 103, 
            'summary' => "This module show an alternative grid system in multiple images or files",
            'href' => 'https://github.com/LuisSantiago/altGrid',
            'author' => 'Blad',
            'autoload' => true
            );
    }

    public function init() {
            $this->addHookBefore('InputfieldImage::render', $this, 'altGridconfigBefore');
        }
        
     public function altGridconfigBefore(HookEvent $event) {
                $this->config->scripts->add($this->config->urls->altGrid . 'altGrid.js'); 
                $this->config->styles->add($this->config->urls->altGrid . 'altGrid.css');                             
         }

     static public function getModuleConfigInputfields(array $data) {
		$inputfields = new InputfieldWrapper();
		$data = array_merge(self::$defaultConfig, $data); 

		$fi = wire('modules')->get('InputfieldText'); 
		$fi->attr('name', 'marginfield');
		$fi->attr('value', $data['20px']); 
		$fi->label = __('Images margin-right:'); 
		$inputfields->add($fi);
		
		$fi = wire('modules')->get('InputfieldText'); 
		$fi->attr('name', 'percentfield');
		$fi->attr('value', $data['30%']); 
		$fi->label = __('porcentaje de anchura  por defecto de las imágenes:'); 
		$inputfields->add($fi);

		return $inputfields;
	}

    
    
}
